---
language: python

python:
  - 3.6
  - 3.8

env:
  global:
    - TEST_DIR="$TRAVIS_BUILD_DIR/tmp"
  matrix:
    - NUMPY_SPEC='numpy==1.16'
    - NUMPY_SPEC='numpy'

jobs:
  include:
    - stage: test
      install:
        - pip install $NUMPY_SPEC
        - pip install pytest pytest-cov codecov
        - pip install .
      script:
        - ci/travis_test.sh
        - bash <(curl -s https://codecov.io/bash)
    - stage: linting
      install:
        - pip install flake8
        - flake8 .
      python: 3.8
      NUMPY_SPEC: 'numpy'
